### ISSUE TITLE
رفع مشکل دانلود فایل‌های بک‌آپ

### ISSUE THREAD

**Issue by ohmydevops** [Hameds/GoogleBackup#1]
<div dir='rtl'>

بعد از درخواست ایجاد فایل بک‌آپ، گوگل ایمیل میزنه که فایل شما آماده است و من موقع دانلود فایل به ارور ۴۰۳ خوردم. با یکی دو تا VPN تست کردم تا بالاخره ProtonVPN مشکلم رو حل کرد.

</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

دوستی وضعیت نشتی‌های ممکن رو اضافه کردند. اگر فکر می‌کنید این VPN نشتی نداره (بر اساس سایت‌هایی که جهت تست نشتی معرفی شده) لطفاً به بخش VPNهای تست شده اضافه کنید

</div>

**Comment by Kiavash-team** [comment]
windscribe 
سرور انگلیس تست کردم برای دانلود مشکلی نداشت!

**Comment by Hameds** [comment]
@Kiavash-team ممنون. به لیست اضافه شده
