### ISSUE TITLE
Google 2-Step Verification

### ISSUE THREAD

**Issue by hvmidrezv** [Hameds/GoogleBackup#13]
سلام تو این چند روز که این مشکلات به وجود اومدن من متوجه شدم دیگه پیغام تایید دومرحله‌ای که با یه کلیک راحت انجام میشد 
(Google prompt)
هم به گوشی ارسال نمیشه و حتما باید کد پیامک بشه اگه این سرویس حساب میشه در صورت لزوم اضافه کنید، ممنون

**Comment by Hameds** [comment]
ممنونم. به لیست سرویس‌های تاثیر گرفته اضافه شد
