### ISSUE TITLE
اصلاح لینک گوگل پسوردز

### ISSUE THREAD

**Issue by ihamedm** [Hameds/GoogleBackup#16]
تو این پاراگراف لینک رو اصلاح کنید 

> ⚠️ نکته مهم: اگر کلمات عبور خود را روی مرورگر کروم ذخیره کردید به آدرس Google Password Manager رفته و یک نسخه پشتیبان تهیه کنید.

**Comment by Hameds** [comment]
ممنون از شما. انجام شد
