### ISSUE TITLE
نگهداری فایل‌های بک‌آپ و اطلاعات حساس بدون هیچ‌گونه لایه محافظتی

### ISSUE THREAD

**Issue by ohmydevops** [Hameds/GoogleBackup#2]
<div dir='rtl'>

احتمالا بعد از دانلود فایل‌های بک‌آپ و پسورد‌ها، اکثر کاربران روی دسکتاپشون اطلاعات رو دائم یا موقت نگه‌دارند. این موضوع میتونه خطرناک باشه و بهتره که کاربران اطلاعاتشون رو رمزنگاری کنند و از اطلاعات‌شون محافظت کنند. خوبه که توی توضیحات این موضوع حتما گوشزد بشه

</div>

**Comment by Hameds** [comment]
اینو نوشتم احتمالاً در فاصله کامیت‌ها دیده نشده

**Comment by ohmydevops** [comment]
ممنون حامد جان. اره من متوجه کامیت اخر نشدم.
