### ISSUE TITLE
فلگ شدن ای پی‌های ایرانی

### ISSUE THREAD

**Issue by samatamazhori** [Hameds/GoogleBackup#20]

**Comment by Hameds** [comment]
بیشتر توضیح می‌دین؟

**Comment by xhdix** [comment]
<div dir="rtl">
 احتمالا به خاطر ذره بین باشه یا Active probing اما به نظر از IP های معمولی ایرانی استفاده می کردن.
</div>

**Comment by xhdix** [comment]
![image](https://user-images.githubusercontent.com/12384263/113509947-d9e51480-9560-11eb-88ca-ffc275c9ffe2.png)
![image](https://user-images.githubusercontent.com/12384263/113509975-013be180-9561-11eb-9412-ef2af6fbec65.png)

**Comment by Hameds** [comment]
آیا این همچنان ادامه داره؟ از طرفی به نظر نمی‌رسه که مرتبط با مشکل 403 باشه

**Comment by xhdix** [comment]
<div dir="rtl"> 
برای من نه، اما اولین بار بود که چنین خطایی دیده بودم. و  تقریبا همزمانی اش با اون اتفاق عجیب بود برام.
</div>

**Comment by Hameds** [comment]
این توییت هم به این موضوع اشاره کردند

https://twitter.com/reza3320/status/1384772228026441728

**Comment by xhdix** [comment]
<div dir="rtl">و این از @behdad222 : </div>

![image](https://user-images.githubusercontent.com/12384263/116779993-467d0180-aa82-11eb-8d20-3cf33abdf7d2.png)

https://twitter.com/behdad222/status/1387427873598976000

**Comment by behdad222** [comment]
@xhdix 
یعنی میگی این دستکاری جهرمی برای فیلترینگ نیست!؟

به نظرم منطقی میاد

**Comment by xhdix** [comment]
<div dir="rtl">
@behdad222 :
به خاطر HTTPS بودنش و با توجه به میزان آشنایی شما با امنیت، و همچنین استفاده نکردن از DNS پیشفرض و محتمل نبودن SmartDNS برای مقابله با تحریم توسط خدمات دهنده ی اینترنت، نمیتونه دستکاری شبکه دخیل باشه. تنها موردی که میتونه باعث این بشه که چنین خطایی دریافت کنید این هست که از قبل با این IP بهشون حمله شده باشه.
<br>
امروز به جای حمله در لایه ی application، در لایه ی شبکه انجام شده بوده. و به عبارتی احتمالا از این به بعد به جای خطای 429 ممکنه هیچ جوابی دریافت نکنید و یا RST باشه.
</div>


https://twitter.com/xhdix/status/1388450115275399171

**Comment by behdad222** [comment]
@xhdix

بسیار عالی
البته تو این تست dns پیشفرض بود

**Comment by xhdix** [comment]
<div dir="rtl">

>  البته تو این تست dns پیشفرض بود

تست Websites در OONI میتونه تفاوت IP در جواب DNS را با جواب در خارج از شبکه تشخیص بده. اگه دوباره پیش اومد تست کنید عالی میشه.
</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

با توجه به اینکه به نظر نمی‌رسه مرتبط با Google403 باشه، فعلاً این رو خاتمه می‌دم. اگر شواهدی درباره ارتباط این مساله با مشکل 403 بود بفرمایید تا مجدد باز بشه

</div>
