### ISSUE TITLE
Replacement Solutions

### ISSUE THREAD

**Issue by 1995parham** [Hameds/GoogleBackup#23]
I think it will be great if we can provide some replacement solutions and motivate people to migrate using them.

**Comment by 0xRustlang** [comment]
خیلی وجود داره ولی متاسفانه مثلا توی قسمت ایمیل مایکروسافت هم امن نیست (قضیه گیت هاب)

من خودم الان صرفا برای یه سری اکانتایی که دیگه از دستم در رفته از اکانتای گوگلم استفاده میکنم و برای گوگل درایو چون‌پول خرید سرور و... ندارم و البته حجم سرویسای مشابه درایو کمه یا اینکه محدودیت چندماهه دارن برای ریمو کردن اکانت درصورت غیرفعال بودن

برای مثال مگا و پی کلود محدودیت سه ماهه یا شش ماهه داشتن اگر یادم باشه و حتی مدیافایر که نشنیده بودم پاک کنه و حتی توی سایتای خارجی نوشته بودن پاک‌نمیکنه دیتاهای اکانتای غیرفعال رو، اچن هم پاک کرده بود اکانتم رو بعد شاید یکسال یا شش ماه لاگین نکردن

**Comment by 0xRustlang** [comment]
برای یادداشت استاندارد نوت هست
برای مروگر و سینک فایرفاکس

**Comment by 1995parham** [comment]
Exactly, some services need payment. Firefox is great and also emacs org-mode is awesome for writing notes and to-do list. Also instead of dropbox Synthing is great but you need to have cloud storage if you want a cloud backup.

**Comment by Hameds** [comment]
Here is a really huge list of alternatives to google products: https://degoogle.jmoore.dev/
