### ISSUE TITLE
تاریخچه مشکل 403 گوگل

### ISSUE THREAD

**Issue by xhdix** [Hameds/GoogleBackup#25]
<div dir="rtl">
اولین باری که این مشکل مشاهده شده (۹ اسفند ۱۳۹۹):
</div>
<a href="https://twitter.com/xhdix/status/1365406646806204420"> https://twitter.com/xhdix/status/1365406646806204420</a>
<p>

</p>

<div dir="rtl">
اون لینک توییتر از خطای 404 برای همه قابل دیدن نیست، میتونید از این استفاده کنید:
</div>
<a href="https://twitter.com/xhdix/status/1377625667332870150"> https://twitter.com/xhdix/status/1377625667332870150</a>
<p>

</p>

<div dir="rtl">
این هم در مورد این هست که علاوه بر تحریم، مشکلاتی هم برای کلاد گوگل به نظر پیش آمده
</div>
<a href="https://twitter.com/xhdix/status/1377368989492338691"> https://twitter.com/xhdix/status/1377368989492338691 </a>

**Comment by behdad222** [comment]
روند تشخیص یوزرهای ایرانی در پلی استور

![image](https://user-images.githubusercontent.com/3942191/113511058-2c2f3100-9573-11eb-860d-daf6b2de1eb7.png)

**Comment by xhdix** [comment]
<div dir="rtl">
مربوط به چه اپی هست؟ 
<br>
برای سرور من از ماه فوریه شروع شده.
</div>

**Comment by behdad222** [comment]
برا همین برام عجیبه
تو خیلی زود به مشکل خوردی
یه اپ دیگه هم دارم که مطابق با همینه
حتی اون پایین رفتنش
https://play.google.com/store/apps/details?id=com.byagowi.persiancalendar

**Comment by xhdix** [comment]
<div dir="rtl">
من این سرور ام فکر کنم نزدیک یک سال شاید فعال بوده و حدود 10 تا کاربر همیشه فعال داشته.
<br>
مزیت اش این بود که در range IP/24 ای بود که بعضی مراکز آپا روش VPN داشتن. معمولا کمتر براش مشکل پیش میومد. :grin: 
<br>
این افزایش نصب شاید به خاطر این باشه که مردم نوروز گوشی نو خریدن! چون 3 فروردین میشه دیگه؟
</div>

**Comment by xhdix** [comment]
<div dir="rtl">
طبق بررسی داخلی گوگل، IPی سرور من از  18 فوریه معادل ۳۰ بهمن در دیتابس داخلی گوگل به عنوان ایران در نظر گرفته شده. اما اکثر کاربرها از 24 مارس معادل ۴ فروردین :
</div>

![image](https://user-images.githubusercontent.com/12384263/113659567-fa20ea80-96aa-11eb-89fc-76c824b2d6b9.png)

https://transparencyreport.google.com/traffic/overview?fraction_traffic=start:1609459200000;end:1617753599999;product:21;region:IR&lu=fraction_traffic

**Comment by Hameds** [comment]
<div dir='rtl'>

من عنوان این رو عوض می‌کنم به تاریخچه مشکل و لینکی رو در Readme هم اضافه می‌کنم. فعلاً خاتمه می‌دم اگر درباره تاریخچه شواهد دیگه‌ای هم بود بعد دوباره اضافه‌اش می‌کنیم.

</div>
