### ISSUE TITLE
Reverse dns/ip lookup

### ISSUE THREAD

**Issue by Abolfazl74** [Hameds/GoogleBackup#26]
<div dir='rtl'>

قکر میکنم از طریق Reverse dns/ip lookup اینکارو میکنن و تقریبا میشه گفت هیچ راهی برای جلوگیریش وجود نداره به جز استفاده از vpn  های شخصی یا استفاده موقت از vpn های مختلف و عوض کردنش چون گوگل از یه تعدادی به بعد واسه محدود کردن آی پی های مخصوص فقط به یک کشور مجبوره از سر لیست آی پی های اول رو حذف بکنه(حداقل پرایوریتی های پایین تر رو) چون به تدریج رنج آی پی هایی بن میشن که دیگه واسه VPN استفاده نمیشن
جدا از اطلاعاتی که خود isp ها با توجه به سیاستشون از آی پی هاشون لیک میکنن سرویس های زیادی وجود دارن در اصل کارشون لیک کردن همین اطلاعاته
از نظر من مسأله مهمی نیست میتونم بگم گوگل با این کارش بیشتر به ایرانیا هشدار استفاده از vpn های معتبر رو داده :))
میدونین این مساله کی خطرناک میشه؟ زمانی که ipv4 از دور خارج بشه :))
در هر صورت این توضیحات در حد سواد بنده بود خوشحال میشم نظراتتون رو بشنوم

</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

گزارش‌هایی داریم که سرورهای پروکسی شخصی و VPNهای شخصی هم دچار مشکل شده و 403 دریافت می‌کنند 

</div>

**Comment by Abolfazl74** [comment]
> <div dir='rtl'>
> 
> 
> 
> گزارش‌هایی داریم که سرورهای پروکسی شخصی و VPNهای شخصی هم دچار مشکل شده و 403 دریافت می‌کنند 
> 
> 
> 
> </div>
خیلی عجیبه
چون گوگل در حال حاظر پروکسی های خیلی پر استفاده مثل اکستنشن SetupVpn رو هم وقتی آی پی هاشونو عوض میکنن تشخیص نمیده و صرف مرور زمان و سیاست لیکرهاش بن میکنه
این که عرض کردم شخصی باشه پیکربندی مناسب اگر نداشته باشه یا ISP که استفاده میکنه مخصوص سرورای VPN باشه قطعا راحت شناسایی میشه
اگر جز اینها باشه تنها چیزی که به ذهن بنده میرسه سو استفاده گوگل به هر نحوی از مرورگرش یعنی کروم هست :)))
