### ISSUE TITLE
Waze + Google Family

### ISSUE THREAD

**Issue by ghermez** [Hameds/GoogleBackup#27]
به لیست سرویس هایی که از دسترس خارج شدند مسیریاب ویز و google family رو اضافه کنید
من از اپ گوگل فمیلی برای کنترل تبلت بچه ام استفاده میکردم که از همون اول هم با وی پی ان کار میکرد
با توجه به اینکه من هیچ نشتی از سرور نداشتم ولی باز هم این دو سرویس از روز شنبه از دسترس من خارج شدند

**Comment by Hameds** [comment]
ممنون که تجربه‌تون رو به اشتراک گذاشتید. به لیست سرویس‌های تاثیر گرفته اضافه می‌کنم
