### ISSUE TITLE
docs.gitlab.com

### ISSUE THREAD

**Issue by m-yosefpor** [Hameds/GoogleBackup#29]
We cannot access https://docs.gitlab.com with VPN

**Comment by toghani** [comment]
> We cannot access https://docs.gitlab.com with VPN

NP, I have access

**Comment by m-yosefpor** [comment]
Yeah fixed with changing my VPN protocol to OpenVPN. However I used to have access to this with HiSpeed protocol, but can't do anymore (other censored/sanctioned websites are still ok  with my HiSpeed)
