### ISSUE TITLE
Google Podcasts

### ISSUE THREAD

**Issue by Hashemian01** [Hameds/GoogleBackup#31]
فکر می‌کنم گوگل پادکست هم تحت تاثیر قرار گرفته. با دو تا اکانت مختلف امتحان کردم که از یکیش مرتب استفاده می‌کنم و از اون یکی به ندرت. هر دو با اکسپرس وی پی ان
![image](https://user-images.githubusercontent.com/48093461/113563600-3a398c00-961d-11eb-9caf-1b9c5c8729f3.png)

**Comment by Hameds** [comment]
ممنون از اینکه تجربه‌تون رو به اشتراک گذاشتید. به لیست سرویس‌های تاثیر گرفته اضافه می‌کنم
