### ISSUE TITLE
GMail and Google Account

### ISSUE THREAD

**Issue by Amm1rr** [Hameds/GoogleBackup#34]
<p dir="rtl">
من جیمیل و کلا همه قسمت‌های تنظیمات گوگل اکانتم به همین شکل است.
جالب اینکه من خارج از ایران هستم و فقط وقتی با اکانتم بخوام لاگین بکنم همه مشکلات برام پیش میاد.
وقتی لاگین نکنم مشکلی وجود نداره.
یوتوب برام باز میشه، ولی نمیتونم لاگین کنم.
</p>
: )

**Comment by Hameds** [comment]
<div dir='rtl'>

ممکنه تصویری از خطای دریافتی ارسال بفرمایید؟ و اینکه این از چه زمانی ایجاد شد؟ همچنین آیا در این مدت از VPN استفاده کردید؟

</div>

**Comment by Amm1rr** [comment]
<p dir="rtl">
الان اومدم عکس بگیرم از صفحه دیدم فعلا درست شده، چون امروز دوبار اکانتم خودکار لاگ‌آوت شده.
ولی من این اکانت رو تو ایران ساختم و استفاده میکردم تا ۲ و ۳ سال پیش.
استفاده VPN هم نداشتم.
</p>

**Comment by Amm1rr** [comment]
<p dir="rtl">
نخیر!<br>
فقط کمی بهتر شده!<br>
فقط دسترسیم به GMail  و YouTube بهتر شده، در حین استفاده یکدفعه هیچ Response ای دریافت نمی‌کنم.<br>
ولی وقتی یک پنجره جدید باز میکنم که باهاش لاگین نکردم هیچ مشکلی وجود نداره.<br>
هنوز اکانت دومم رو نمیتونم باهاش حتی توی GMail هم  بکنم و فقط صفحه درحال Refresh میمونه بدونه Timeout.
وقتی هم میخوام حتی بصورت imap.gmail.com بازش کنم به یوزر و پسووردم خطا میده!<br>
برای اکونت اولم هم اصلا <a href="https://keep.google.com/" target="_blank">Google Keep</a> رو نمیتونم باز کنم فقط GMail و YouTube تقریبا درست شده.<br>
همچنان دسترسی به Google Account برای تنظیمات Account های Google ام از هر ۳۰ الی ۴۰ بار تلاش در روز، فقط یکبار موفقیت آمیز است.<br>
و یک نکته دیگه اینکه این مشکل با توییتر هم پیدا کردم! قالب کلی توییتر باز میشه ولی محتویاط توییتر مثل توییت‌ها درحال بارگذاری باقی میمونه. بصورت اتفاقی بعضی مواقع درست میشه که در اون موقع گوگل هم برام درست شده!<br>
</p>

![Google-Keep](https://user-images.githubusercontent.com/480468/113851936-47c95000-979c-11eb-9657-48f8cd189ac7.jpg)

**Comment by poyynt** [comment]
به نظر می‌رسه مشکل شما بیشتر مربوط به فیلترشکن یا اینترنت‌تون باشه تا تحریم گوگل.

**Comment by Amm1rr** [comment]
<p dir="right">
اتفاقا با چندتا سرویس‌دهنده دیگه هم تست کردم ولی همه چیز درسته تا وقتی که لاگین نکردم.
تا لاگین کنم سرویس دهی قطع میشه.
</p>

**Comment by Hameds** [comment]
@Soheyl آیا این مساله همچنان ادامه داره؟ با توجه به اینکه می‌فرمایید در سایت‌های دیگری هم مشکل دارید (که لزوماً مرتبط با گوگل یا زیرساخت ابری گوگل نیستند) به نظر نمی‌رسه مربوط به مشکل خطای ۴۰۳ گوگل باشه

**Comment by Amm1rr** [comment]
<div dir="rtl">
بله همچنان ادامه داره، فقط کمی بهتر شده. با هر سایتی که بخواد به گوگل وصل بشه و چیزی رو چک بکنه مشکل دارم.<br>
منظورم Login As Google هستتش. بعنوان مثال همین گیت‌هاب رو از روزی که شما پست آخر رو زدی تا همین الان نتونستم لاگین کنم تا جواب بدم.<br>
به گوگل ایمیل زدم ولی هنوز پاسخی ندادن.<br>
حسی که من به این مشکل دارم اینه که از زمان این ماجرای VPN یه باگی چیزی باعث مشکل شده.<br>
الان درست شده، ولی دفعه دیگه که به مشکل بخورم میخوام یه اکانت جدید بسازم تا ببینم این مشکل برای اون هم وجود داره یا نه. نتیجه رو اعلام میکنم.
</div>

**Comment by Hameds** [comment]
ممنون از شما. امیدوارم مساله حل بشه. من این رو خاتمه می‌دم اگر دوباره ایجاد شد لطفاً دوباره اطلاع بدید تا در صورت نیاز اطلاع‌رسانی کنیم
