### ISSUE TITLE
Google Takeout

### ISSUE THREAD

**Issue by DavodOsanlo** [Hameds/GoogleBackup#35]
من به خاطراینکه گوگل اکانت من رو کاملاً ایران تشخیص داده( حتی با وی‌پی‌اس شخصی) حتی نمی‌تونم دیتاهایی که داشتم رو دانلود کنم و ارور ۴۰۳ می‌گیرم

**Comment by Hameds** [comment]
متاسفانه این مشکل وجود داره. در بخش سوالات متداول توضیح داده شده که چه کار می‌تونید انجام بدین
