### ISSUE TITLE
محتویات فایل بک‌آپ شامل چه چیزهاییه؟

### ISSUE THREAD

**Issue by ohmydevops** [Hameds/GoogleBackup#4]
<div dir='rtl'>

اگر براتون سواله که توی فایل بک‌آپ چه چیزهایی قرار داره برای من مهم‌ترین‌هاش این‌ها بود:

- عکس‌هایی که توی گوگل‌فوتوز آپلود کردید +‌ فایل‌های متادیتاشون
- تمام ایمیل‌هاتون با فرمت Mbox موجوده که میتونید توی کلاینت‌ها مشاهده کنیدشون.
- کانال‌هایی که توی یوتیوب دنبال کردید یا پلی لیست‌ها یا حتی ویدیو‌هایی که لایک کردید و ... همگی به صورت json وجود داره.
- تمام فایل‌های گوگل درایو
- لیست کانتکت‌هاتون با فرمت VCF
- چت‌های hangout و فایل‌هاش

![Capture](https://user-images.githubusercontent.com/21690865/113487292-7d381a00-94cc-11eb-8db3-0747bd822b29.PNG)

</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنون بابت توضیحات. لطفاً توضیحات و تصویر رو در قالب PR ارسال کنید

</div>
