### ISSUE TITLE
راه حل چیه؟

### ISSUE THREAD

**Issue by ghermez** [Hameds/GoogleBackup#42]
سلام
خوب ما تو این چند روز تقریبا فهمیدیم که چه سرویس هایی از دسترس خارج شده
دوستان متخصص هم قاعدتا فهمیدن که از نظر فنی چه اتفاقی داره میوفته و یا حداقل حدس های قریب به یقین دارن

الان راه حل چیه؟
چطور میتونیم اون تحریم ها رو دور بزنیم؟
چه راه حل عمومی میشه برای این مشکل پیشنهاد داد؟
برای کسانی که سرور خصوصی دارن چه راهکار عملی پیشنهاد میشه؟

**Comment by NimaAram1** [comment]
سلام
من با این dns به راحتی با فایربیس و بقیه سرویس ها کار کردم
https://shecan.ir/

**Comment by Hameds** [comment]
<div dir='rtl'>

این مساله از سمت کاربران راه‌حلی نداره. یعنی اگر IP سرور اختصاصی شما از طرف گوگل flag شده باشه یا روی حساب کاربری سرویسی معلق شده باشه به جز مکاتبه با گوگل (که امید چندانی هم بهش نیست) راه حلی نیست.

اگر برنامه‌نویس هستید [fodev](http://fodev.org) رو هم چک کنید

در #56 هم یکی از دوستان کدی رو نوشته با این حال عرض می‌کنم در سمت ما به جز اطلاع‌رسانی به دیگران (جهت اینکه مشکل کمتر براشون پیش بیاد و هوشیار باشن نسبت به موضوع) و تغییر حساب/سرور دسترسی به سرویس‌ها راه دیگه‌ای در حال حاضر به نظر نمیاد

</div>
