### ISSUE TITLE
New 403 Error

### ISSUE THREAD

**Issue by seyedmm** [Hameds/GoogleBackup#43]
<div dir=rtl>

هنگام ساختن حساب کاربری در [جئوجبرا](https://geogebra.org) به ارور **_403_** برمیخورم. البته این ارور همیشگی نیست و گاها پیش نمی آید. در دو مکان به این ارور بر میخورم:

1. باز کردن صفحه ثبت نام
2. تایید ایمیل

قابل توجه است که جئوجبرا از کلادفلیر استفاده میکند. خواهشا به لیست اضافه شود

**Comment by Hameds** [comment]
<div dir='rtl'>

آیا روی زیرساخت ابری گوگل (GCP) قرار دارد؟

</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

@seyedmm 
آیا خطای 403 از این نوع است؟

![403](https://repository-images.githubusercontent.com/354351350/0459b200-950e-11eb-9a84-f5609b5e21d4)


</div>

**Comment by seyedmm** [comment]
<div dir=rtl>
 @Hameds
درباره اینکه آیا روی GCP است یا نه اطلاعاتی ندارم. اما خطا از آن نوع نیست. یعنی خود وبسایت یک صفحه 403 ساده با چند خط متن حاضر کرده و آنرا نمایش میدهد.

**Comment by Hameds** [comment]
@seyedmm ضمن تشکر چون این خطا از نوع خطاهای اشاره شده 403 گوگل نیست و با توجه به اینکه من هم چیزی پیدا نکردم که این سرویس روی زیرساخت ابری گوگل باشه، به نظر می‌رسه این خطای 403 به موضوع تغییر شیوه شناسایی محل کاربران در گوگل مرتبط نباشه. بر این اساس ایشو رو خاتمه می‌دم. لطفاً اگر شواهد جدیدی در این خصوص بود بفرمایید
