### ISSUE TITLE
YouTube Music

### ISSUE THREAD

**Issue by ghost** [Hameds/GoogleBackup#44]
[یوتیوب میوزیک](https://music.youtube.com/) هم به این شکل دراومده برای من، با وی پی ان ثابت کانادا که همیشه استفاده میکردم
![Screenshot from 2021-04-09 01-36-30](https://user-images.githubusercontent.com/20649/114096552-1e134480-98d4-11eb-857f-25712f8cf819.png)

**Comment by Hameds** [comment]
لطفاً این رو بخونید و بفرمایید تایید می‌کنید یا هنوز 403 می‌گیرید؟
https://twitter.com/NomadCR34/status/1380392698763431944

**Comment by ghost** [comment]
بله هنوز هم این خطا رو می‌گیرم
البته من یه تست دیگه انجام دادم برای اینه بفهمم آشکار شدن لوکیشن روی اکانت هم تاثیر داره یا نه
با وی پی ان روی یک سرور جدید، با همین اکانت فعلی هیچ مشکلی برای دسترسی ندارم (هر دو نسخه وب و اپ)
ولی روی وی پی ان قبلی حتی با اکانتی که هیچ سابقه‌ای از ایران توش نیست. خطا میگیرم

**Comment by Hameds** [comment]
<div dir='rtl'>

سپاس از شما. اضافه شد.

یک توضیح رو به زودی اضافه می‌کنم. این بسته شدن دسترسی در سرویس‌های مختلف متفاوته بعضی‌ها بر اساس IP و بعضی بر اساس اکانت و بعضی بر اساس ترکیب ۲ مورد است.

</div>
