### ISSUE TITLE
Service or website checked - 21-04-09

### ISSUE THREAD

**Issue by NomadCR34** [Hameds/GoogleBackup#47]
Website or service | with Blocked IP | with IP of Iran |
| ------------- | ------------- |------------- |
| developers.google | opened  | opened |
| android developers | error 403  | error 403 |
| cloud.google | error 403  | error 403 | 
| firebase | error 403  | error 403 |
| developers.google.com/assistant | opened | error 403 |
| developers.google.com/maps | opened  | opened |
| developers.google.com/web | opened  | error 403 |
| developers.google.com/analytics | opened  | error 403  |
| developers.google.com/google-ads | opened  | opened |
| tensorflow.org/tutorials | error 403 |  error 403 |
| youtube kids | opened | - |
| youtube music | opened | - |
| spotify | error 403 | opened |
| kaggle | error 403 | error 403 |
| last.fm |  error 403 | - |
| podcasts.google | opened | opened |
| castbox | opened | opened |
| google scholar | opened | opened |
| google play book | opened | books on google play is not available in your country |
| google workspace | opened | opened | 
| firebase auth | error 403 | error 403
| slite | error 403 | error 403 |
| grafana | error 403 | - |

**Comment by Hameds** [comment]
منظور شما اینه که با آی پی بلاک شده بعد از مدتی براتون باز شده؟

**Comment by NomadCR34** [comment]
> منظور شما اینه که با آی پی بلاک شده بعد از مدتی براتون باز شده؟

بله
البته سایت و اپلیکیشن اسپاتیفای کاملا بر عکس داره عمل میکنه برای من .بعد از باز شدن سرویس هایی که تا الان درست شدن با ای پی ایران بدون مشکل باز میشه ولی با ای پی سرور که توسط گوگل بلاک شده هنوز 403 بر میگرده

**Comment by NomadCR34** [comment]
حامد این رو الان تست کردم

اندروید هم برای اون ای پی بلاک شده  باز شده دیروز امکانش نبود sdk امکان دانلود 
ولی همچنان سایت android devبسته هست
 جدول بالا رو آپدیت میکنم

**Comment by NomadCR34** [comment]
**update 21-04-10**

Website or service | with Blocked IP | with IP of Iran |
| ------------- | ------------- |------------- |
| developers.google | opened  | opened |
| android developers | error 403  | error 403 |
| android sdk | opened | - | 
| go lang | error 403 | error 403 | 
| cloud.google | error 403  | error 403 | 
| firebase | error 403  | error 403 |
| developers.google.com/assistant | opened | error 403 |
| developers.google.com/maps | opened  | opened |
| developers.google.com/web | opened  | error 403 |
| developers.google.com/analytics | opened  | error 403  |
| developers.google.com/google-ads | opened  | opened |
| tensorflow.org/tutorials | error 403 |  error 403 |
| youtube kids | opened | - |
| youtube music | opened | - |
| spotify | error 403 | opened |
| kaggle | error 403 | error 403 |
| last.fm |  error 403 | - |
| podcasts.google | opened | opened |
| castbox | opened | opened |
| google scholar | opened | opened |
| google play book | opened | books on google play is not available in your country |
| google workspace | opened | opened | 
| firebase auth | error 403 | error 403
| slite | error 403 | error 403 |
| grafana | error 403 | - |

**Comment by xhdix** [comment]
<div dir="rtl">
میتونید این موارد را بدون VPN برای اون دسته از آدرس هایی که با VPN مشکل دارید اما مستقیم نه، امتحان کنید؟
</div>

```sh
dig www.spotify.com
dig +tcp www.spotify.com @9.9.9.9

curl -I https://www.spotify.com
curl -I --doh-url https://doh.powerdns.org https://www.spotify.com
```

**Comment by NomadCR34** [comment]
**dig www.spotify.com**
`
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16466
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.spotify.com.		IN	A

;; ANSWER SECTION:
www.spotify.com.	250	IN	CNAME	edge-web-split-geo.dual-gslb.spotify.com.
edge-web-split-geo.dual-gslb.spotify.com. 99 IN	A 35.186.224.25

;; Query time: 411 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun Apr 11 09:37:07 +0430 2021
;; MSG SIZE  rcvd: 103
`



**dig +tcp www.spotify.com @9.9.9.9**
`
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56074
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.spotify.com.		IN	A

;; ANSWER SECTION:
www.spotify.com.	239	IN	CNAME	edge-web-split-geo.dual-gslb.spotify.com.
edge-web-split-geo.dual-gslb.spotify.com. 89 IN	A 35.186.224.25

;; Query time: 131 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Sun Apr 11 09:45:16 +0430 2021
;; MSG SIZE  rcvd: 103
`



**curl -I https://www.spotify.com**
`
HTTP/2 301 
date: Sun, 11 Apr 2021 05:15:45 GMT
content-type: text/html
content-length: 162
location: https://www.spotify.com/de/
set-cookie: sp_m=de; Path=/; Domain=.spotify.com; Max-Age=115516800; Expires=Sun, 08 Dec 2024 05:15:45 GMT; Secure; HttpOnly; SameSite=Lax
sp-trace-id: e90088b47b42f5cf
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
vary: Accept-Encoding
server: envoy
via: HTTP/2 edgeproxy, 1.1 google
alt-svc: clear

`



**curl -I --doh-url https://doh.powerdns.org https://www.spotify.com**
`
HTTP/2 301 
date: Sun, 11 Apr 2021 05:16:23 GMT
content-type: text/html
content-length: 162
location: https://www.spotify.com/de/
set-cookie: sp_m=de; Path=/; Domain=.spotify.com; Max-Age=115516800; Expires=Sun, 08 Dec 2024 05:16:23 GMT; Secure; HttpOnly; SameSite=Lax
sp-trace-id: 728c0a44d710955b
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
vary: Accept-Encoding
server: envoy
via: HTTP/2 edgeproxy, 1.1 google
alt-svc: clear

`

**Comment by xhdix** [comment]
<div dir="rtl">
جالبه! 
برای ایران به آلمان redirect می کنه!
اما من وقتی با Tor با چند بار امتحان Exit-node را روی آلمان گذاشتم باز هم رفت روی آمریکا!
</div>


![image](https://user-images.githubusercontent.com/12384263/114313687-2ea80280-9b00-11eb-8457-c8dc0c533df3.png)

<div dir="rtl">
فکر می کردم موضوع SmartDNS در میان باشه اما این تغییرات در خود گوگل هست.
</div>

**Comment by ghermez** [comment]
> میتونید این موارد را بدون VPN برای اون دسته از آدرس هایی که با VPN مشکل دارید اما مستقیم نه، امتحان کنید؟
> ```shell
> dig www.spotify.com
> dig +tcp www.spotify.com @9.9.9.9
> 
> curl -I https://www.spotify.com
> curl -I --doh-url https://doh.powerdns.org https://www.spotify.com
> ```

 dig www.spotify.com

; <<>> DiG 9.16.1-Ubuntu <<>> www.spotify.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16278
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.spotify.com.               IN      A

;; ANSWER SECTION:
www.spotify.com.        1800    IN      CNAME   edge-web-split-geo.dual-gslb.spotify.com.
edge-web-split-geo.dual-gslb.spotify.com. 1800 IN A 35.186.224.25

;; Query time: 188 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 13 10:46:07 UTC 2021
;; MSG SIZE  rcvd: 103

~# dig +tcp www.spotify.com @9.9.9.9

; <<>> DiG 9.16.1-Ubuntu <<>> +tcp www.spotify.com @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38058
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.spotify.com.               IN      A

;; ANSWER SECTION:
www.spotify.com.        300     IN      CNAME   edge-web-split-geo.dual-gslb.spotify.com.
edge-web-split-geo.dual-gslb.spotify.com. 150 IN A 35.186.224.25

;; Query time: 76 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Tue Apr 13 10:47:41 UTC 2021
;; MSG SIZE  rcvd: 103

~# curl -I https://www.spotify.com
HTTP/2 403
content-type: text/html; charset=UTF-8
referrer-policy: no-referrer
content-length: 1579
alt-svc: clear

~# curl -I --doh-url https://doh.powerdns.org https://www.spotify.com
HTTP/2 403

**Comment by xhdix** [comment]
<div dir="rtl">

@mhalizade 
این با VPN هست یا بدون اون؟

</div>

**Comment by mhalizade** [comment]
> @mhalizade
> این با VPN هست یا بدون اون؟

این روی سروری است که به عنوان وی پی ان ازش استفاده میکردم

**Comment by Hameds** [comment]
ممنون بابت پیگیری‌ها. من این رو امروز اطلاع‌رسانی می‌کنم ببینم تجربه مشابهی هست یا خیر

**Comment by NomadCR34** [comment]
یک اپدیت بذارم
android developer 
firebase
 با آی پی بلاک شده از امروز دارن باز میشن
 youtube music
 با ای پی بلاک شده دیگه باز نمیشه و پیام مشابه گوگل بوک رو نشون میده
 نرسیدم برای بقیه موارد چک کنم احتمالا اخر شب بتونم لیست رو مجدد چک کنم

**Comment by NomadCR34** [comment]
update 21-04-16
Website or service | with Blocked IP | with IP of Iran |
| ------------- | ------------- |------------- |
| developers.google | error 403  | error 403 |
| android developers | error 403  | error 403 |
| android SDK | error 403 or 404 | error 403 |
| cloud.google | error 403  | error 403 | 
| firebase | error 403  | error 403 |
| developers.google.com/assistant | error 403 | error 403 |
| developers.google.com/maps | error 403  | opened |
| developers.google.com/web | error 403  | error 403 |
| developers.google.com/analytics | error 403  | error 403  |
| developers.google.com/google-ads | error 403   | opened |
| tensorflow.org/tutorials | error 403 |  error 403 |
| youtube kids | opened | - |
| youtube music | Not Available in your area | - |
| spotify | opened | opened |
| kaggle | opened | error 403 |
| last.fm |  opened | - |
| podcasts.google | opened | opened |
| castbox | opened | opened |
| google scholar | opened | opened |
| google play book | opened | books on google play is not available in your country |
| google workspace | opened | opened | 
| firebase auth | error 403 | error 403
| slite | opened | error 403 |
| grafana | opened | - | 


  از دیروز میشه گفت تمام سرویس هایی که باز شده بودن دوباره بسته شدن

بعضی از سایت های سرویس گیرنده از گوگل وضعیتشون تغییر کرده

**Comment by Hameds** [comment]
ممنون از شما بابت پیگیری

**Comment by ghermez** [comment]
> update 21-04-16
> 
> Website or service	with Blocked IP	with IP of Iran
> developers.google	error 403	error 403
> android developers	error 403	error 403
> android SDK	error 403 or 404	error 403
> cloud.google	error 403	error 403
> firebase	error 403	error 403
> developers.google.com/assistant	error 403	error 403
> developers.google.com/maps	error 403	opened
> developers.google.com/web	error 403	error 403
> developers.google.com/analytics	error 403	error 403
> developers.google.com/google-ads	error 403	opened
> tensorflow.org/tutorials	error 403	error 403
> youtube kids	opened	-
> youtube music	Not Available in your area	-
> spotify	opened	opened
> kaggle	opened	error 403
> last.fm	opened	-
> podcasts.google	opened	opened
> castbox	opened	opened
> google scholar	opened	opened
> google play book	opened	books on google play is not available in your country
> google workspace	opened	opened
> firebase auth	error 403	error 403
> slite	opened	error 403
> grafana	opened	-
> از دیروز میشه گفت تمام سرویس هایی که باز شده بودن دوباره بسته شدن
> 
> بعضی از سایت های سرویس گیرنده از گوگل وضعیتشون تغییر کرده

برای من هیچ کدوم آنبلاک نشدن! نمیدونم ایراد کار کجاست! خیلی مسخره است

**Comment by NomadCR34** [comment]
> > update 21-04-16
> > Website or service	with Blocked IP	with IP of Iran
> > developers.google	error 403	error 403
> > android developers	error 403	error 403
> > android SDK	error 403 or 404	error 403
> > cloud.google	error 403	error 403
> > firebase	error 403	error 403
> > developers.google.com/assistant	error 403	error 403
> > developers.google.com/maps	error 403	opened
> > developers.google.com/web	error 403	error 403
> > developers.google.com/analytics	error 403	error 403
> > developers.google.com/google-ads	error 403	opened
> > tensorflow.org/tutorials	error 403	error 403
> > youtube kids	opened	-
> > youtube music	Not Available in your area	-
> > spotify	opened	opened
> > kaggle	opened	error 403
> > last.fm	opened	-
> > podcasts.google	opened	opened
> > castbox	opened	opened
> > google scholar	opened	opened
> > google play book	opened	books on google play is not available in your country
> > google workspace	opened	opened
> > firebase auth	error 403	error 403
> > slite	opened	error 403
> > grafana	opened	-
> > از دیروز میشه گفت تمام سرویس هایی که باز شده بودن دوباره بسته شدن
> > بعضی از سایت های سرویس گیرنده از گوگل وضعیتشون تغییر کرده
> 
> برای من هیچ کدوم آنبلاک نشدن! نمیدونم ایراد کار کجاست! خیلی مسخره است

چیزی که مشخصه تغییرات هنوز از سمت گوگل در حال انجامه و نمیشه با قطعیت گفت وضعیت کنونی ثابت میمونه
برای مثال سرویس ها دوباره امروز در دسترس قرار گرفتن
حتی فایربیس و اندروید دوو داره با ای پی ایران باز میشه که قبلا فقط با ای پی بلاک شده باز میشد
از طرفی اندروید اس دی کی بعد از دو سه بار گرفتن دیتا از این ادرس
`https://dl.google.com/android/repository/repository2-1.xml`
  درخواست ها رو بلاک میکنه و **ارور ۴۰۴** میده و حتی ۴۰۳ هم نمیده !ولی با این حال میتونم اندروید اسدیو رو از سایتش با ای پی ایران دانلود کنم
golang 
هم همچنان 403 میده

**Comment by mhrdq8i** [comment]
اسپاتیفای و کست‌باکس چرا توو این لیست هستند؟

**Comment by NomadCR34** [comment]
> اسپاتیفای و کست‌باکس چرا توو این لیست هستند؟

در روز های اول شروع شدن مشکل این وب سایت ها هم دچار مشکل و ارور ۴۰۳ بودن که به مرور مشکلشون حل شد

**Comment by NomadCR34** [comment]
یک اپدیت بذارم
golang.org
با ای پی بلاک شده باز میشه
ولی موقع دانلود ۴۰۴ میده
 خیلی از سرویس ها دوباره با همون ای پی بلاک شده باز میشن
 ریپازیتوری های اندروید اس دی کی و گریدل هنوز بسته هستن حتی با ای پی بلاک شده و ارور ۴۰۴ میده    
 نمی دونم واقعا اگر بسته بمونن این سرویس ها امکان پیگیری  هست برامون یا نه

**Comment by Afsaneh1361** [comment]
سلام، بله مشکلات حل میشه

در تاریخ سه‌شنبه ۲۰ آوریل ۲۰۲۱،‏ ۱۷:۴۵ Amin Rooholamini <
***@***.***> نوشت:

**Comment by Afsaneh1361** [comment]
سلام به ایرانیان ،  خوش آمدید



در تاریخ سه‌شنبه ۲۰ آوریل ۲۰۲۱،‏ ۱۵:۱۳ Mehrdad ***@***.***>
نوشت:

**Comment by Afsaneh1361** [comment]
سلام به ایرانیان در خوش امدید


در تاریخ سه‌شنبه ۲۰ آوریل ۲۰۲۱،‏ ۲۳:۰۸ Afsaneh Heydari <
***@***.***> نوشت:

**Comment by Hameds** [comment]
@NomadCR34 برای اندروید و گولنگ احتمالاً تغییر آی‌پی جواب می‌ده
