### ISSUE TITLE
overleaf

### ISSUE THREAD

**Issue by ali-parvizi** [Hameds/GoogleBackup#49]
این وبسایت یه پلتفرم آنلاین هست برای ویرایش و اشتراک گذاری فایل های لاتک،
معمولا فایل ها رو روی این پلتفرم بین همکاران به اشتراک می گذاریم که متاسفانه بعد از این قضیه گوگل دیگه بهش دسترسی ندارم، حتی با فیلتر شکن به طور موقت وصل میشه و خیلی زود دوباره خطای ۴۰۳ رو میده
من اکانتم رو به اکانت گوگل وصل کردم، که الان به نظر میاد کار خیلی اشتباهی بوده
گفتم اطلاع بدم که به لیست اضافه کنید
ممنونم

**Comment by Hameds** [comment]
ممنون از شما. به لیست اضافه می‌کنم
