### ISSUE TITLE
libraries.io

### ISSUE THREAD

**Issue by xmha97** [Hameds/GoogleBackup#52]
افزودن 
https://libraries.io

From IR
![image](https://user-images.githubusercontent.com/23485114/115103010-d50e6080-9f63-11eb-8e47-29aa380d06b0.png)

From US
![image](https://user-images.githubusercontent.com/23485114/115103035-0129e180-9f64-11eb-92f0-5c5a9c6ca83c.png)

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنون از شما. در موضوع خطای 403 مشکل اینجاست که حتی با VPN هم خطای 403 نمایش داده می‌شه و از این جهت سایتی که شما فرمودین شامل این مشکل نیست


</div>
