### ISSUE TITLE
دغدغه های یک برنامه نویس اندروید از طرف گوگل 

### ISSUE THREAD

**Issue by EsmaeeilMoradi** [Hameds/GoogleBackup#53]
<div dir="rtl">

تلفن همراه چیست؟

امروزه چه استفاده‌هایی از تلفن همراه می‌شود ؟

چه نیاز‌هایی از ما رو تلفن همراهمون برطرف می‌کند ؟

حالا نیاز‌های ما رو تلفن همراهمون چطور و  چگونه برطرف می‌کنه ؟

قسمتی زیادی از نیاز‌های ما روی تلفن همراه به وسیله برنامک‌هایی که برنامه‌نویس‌ها می‌نویسن برطرف میشه؟درسته؟

برنامه‌نویس‌ها با استفاده از سرویس‌های  گوگل برنامک‌هایی می‌نویسن که ما با دریافت این سرویس ها نیازهامون برطرف میشه ؟

حالا سرویس‌های گوگل چطور روی تلفن همراه ما دریافت و اجرا میشن؟ یا بهتره بگم برای اینکه تلفن همراهمون سرویس های گوگل رو دریافت کنه باید چه خصوصیتی داشته باشه ؟ آیا باید حتما گوگل پلی‌سرویس روی تلفن همراه من  نصب باشه؟

گوگل پلی سرویس چیه؟ ایا یک برنامک معمولی یه؟  گوگل پلی سرویس کجای تلفن همراه من قرار داره؟ برای اینکه  تلفن همراه من بتونه  سرویس های گوگل رو به دست برنامک‌هایی  که قبلا برنامه‌نویس‌ها توش از سرویس‌های گوگل استفاده کردن و  الان روی تلفن همراه من نصبه و داره نیاز‌های دنیای امروز منو برطرف میکنه چه چیزی نیاز داره؟ گوگل پلی سرویس !!!!!! 

گوگل پلی سرویس به چه قسمت هایی از تلفن همراه من دسترسی داره؟

گوگل پلی سرویس چه رفتاری روی تلفن همراه من داره؟چه اختیاراتی داره؟یا بهتره بگم چه کارهایی روی تلفن همراه من  می تونه انجام بده؟

اگه گوگل به وسیله گوگل پلی سرویس که همواره در حال اجرا هستش به  قسمت‌هایی از تلفن همراه من دسترسی داشته باشه مثلا به فایل‌های من که شامل اطلاعات شخصی من میشه چه اتفاقی می افته؟یا اس ام های من؟یا پیام هایی که توی شبکه‌های اجتماعی ارسال و دریافت می کنم؟

آیا می تونم بگم گوگل  به وسیله گوگل پلی سرویس به کل اطلاعات من دسترسی داره؟

آیا اگه من بخوام از سرویس های گوگل استفاده نکنم می تونم گوگل پلی سرویس رو غیر فعال کنم؟

آیا با غیر فعال کردن گوگل پلی سرویس گوگل دیگه به اطلاعات من دسترسی نداره؟این به این معنی یه که تلفن همراه من یک وسیله مطمعنی یه از هر لحاظ؟

اصلا گوگل پلی سرویس رو تلفن همراه من غیر فعال میشه واقعا؟

اگه گوگل به اطلاعات خانواده من دسترسی داشته باشه می تونم بگم رفتار خانواده من رو می تونه پیش بینی کنه؟می فهمه من و خانواده م قرار چه کار هایی در آینده  انچام بدیم؟یا چه تصمیماتی در آینده قراره بگیریم؟مثلا قرار چی مدل گوشی بخریم؟یا چه مدل لب تاب نیاز ما رو برطرف میکنه؟یا ....؟

حالا اگه بگم می تونه کل محله مون رو پیش بینی کنه حرف درستی زدم؟کل شهر ؟ استان؟ یا حتی کشور چطور؟

آیا فقط من به عنوان یک ایرانی به گوگل اطمینان ندارم؟آیا در کل دنیا این شکلی یه؟

حالا از بحث این اطلاعات بگذریم.!!!!!!!!!!!!!!!!!

حالا اگه ی روز گوگل تصمیم بگیره سرویس هاشو قطع کنه ایا برنامک هایی که بر پایه سرویس های گوگل تهیه شدن می تونن کارایی روی تلفن همراه من داشته باشن؟

اصلا اگه ی روز گوگل بخواد می تونه کاری کنه که تلفن همراه من بلااسفتاده بشه؟

اگه تلفن همراه من بلاا استفاده بشه چه افتاقی می تونه برای من و خانواده من و محله من و شهر من و استان من بی‌افته؟

آیا من فقط تو این دنیا به این چیزا فکر میکنم؟ یا هستن افراد دیگه ای توی کشوری های دیگه....

پس اگه بخوام تلفن همراهمو ایمن کنم از این اتفاقات نیاز دارم یکم مستقل بشم از گوگل .

تا الان به صورت عامیانه خواستم فقط اون چیزا هایی که تو ذهن من بود برای امن کردن یک تلفن همراه بگم.
 </div>

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنونم از شما. دغدغه‌های درستی هستند و بعضی از اون‌ها فقط در ایران باعث نگرانی است. تلاش می‌کنیم مشکلات ناشی از Google 403 رو در این مخزن مستند کنیم. شما هم اگر تجربه‌ای مرتبط با این مساله داشتید لطفاً بفرمایید تا به مخزن اضافه بشه

</div>
