### ISSUE TITLE
بیت‌واردن

### ISSUE THREAD

**Issue by xmha97** [Hameds/GoogleBackup#58]
سلام، یه سوال داشتم (اگر چه می‌دونم این‌جا جاش نیست)
می‌خواستم بدونم بیت‌واردن هم ما رو تحریم کرده؟ چون اصلا سینک نمیشه!
https://bitwarden.com/

**Comment by 0xRustlang** [comment]
مطمئن هستی api هاش فیلتر نیست؟

چون بیت واردن فکرکنم از ساختار azure 
مایکروسافت استفاده میکنه که فکرکنم فعلا مارو تحریم نکرده از لحاظ دسترسی به سروراش البته

**Comment by xmha97** [comment]
> 
> 
> مطمئن هستی api هاش فیلتر نیست؟
> 
> چون بیت واردن فکرکنم از ساختار azure
> مایکروسافت استفاده میکنه که فکرکنم فعلا مارو تحریم نکرده از لحاظ دسترسی به سروراش البته

یه سالی میشه که از بیت‌واردن استفاده می‌کنم و باید بگم هیچ‌وقت فیلتر نشده
الان هم بر اساس سایت شکن، تحریم شدیم:
![image](https://user-images.githubusercontent.com/23485114/118414905-89fb8080-b6bc-11eb-8a56-e20fed9f53ac.png)
و متاسفانه api هاش هم تحریمیم:
https://api.bitwarden.com

**Comment by ahmadalli** [comment]
من به این آدرس ریکوئست می‌زنم هم داخل و هم خارج ایران ارور ۴۰۴ می‌گیرم (ینی احتمالن مشکلی نداره)

**Comment by xhdix** [comment]
<div dir="rtl">
سانسور شده نه تحریم. 
</br>
توضیحات:
</div>

https://twitter.com/xhdix/status/1397104063876112385
