### ISSUE TITLE
A brief list of some of the sanctioned services

### ISSUE THREAD

**Issue by amirdaaee** [Hameds/GoogleBackup#59]
This report is based on [LiDns](https://github.com/amirdaaee/LiDns) records after approximately one month of utilization.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	
</head>

<body>

url | Direct status code | Tor status code
-- | -- | --
odr.mookie1.com | 403 | 200
adeventtracker.spotify.com | 403 | 404
geller-pa.googleapis.com | 403 | 404
addons-pa.clients6.google.com | 403 | 404
rtproxy-row.waze.com | 403 | 404
businesscalls.googleapis.com | 403 | 404
infinitedata-pa.googleapis.com | 403 | 404
tapestry.tapad.com | 403 | 404
firebaseremoteconfig.googleapis.com | 403 | 404
content-autofill.googleapis.com | 403 | 404
analytics.google.com | 403 | 200
phonedeviceverification-pa.googleapis.com | 403 | 404
time.google.com | 403 | 200
maps.googleapis.com | 403 | 200
trc.lhmos.com | 403 | 200
ads.travelaudience.com | 403 | 200
apresolve.spotify.com | 403 | 200
exp.wg.spotify.com | 403 | 200
open.spotify.com | 403 | 404
pixel.spotify.com | 403 | 404
static.apester.com | 403 | 200
sharing-config.spotifycdn.com | 403 | 403
adpushup-d.openx.net | 403 | 200
notifications-pa.googleapis.com | 403 | 404
api.permutive.com | 403 | 404
nrpc.olark.com | 403 | 502
api-partner.spotify.com | 403 | 200
pixel.tapad.com | 403 | 404
ampcid.google.com | 403 | 404
benchmark.1e100cdn.net | 403 | 404
renderer.apester.com | 403 | 404
spclient.wg.spotify.com | 403 | 200
prod.y-medialink.com | 403 | 404
monitoring.clients6.google.com | 403 | 404
tracking.prd.mz.internal.unity3d.com | 403 | 400
gcm.ctnsnet.com | 403 | 404
avowtech.mobileadstrk.com | 403 | 200
subscription.washingtonpost.com | 403 | 404
e2clock.gcp.gvt2.com | 403 | 404
www.deepdyve.com | 403 | 200
console.cloud.google.com | 403 | 200
wallet.google.com | 403 | 200
tr.blismedia.com | 403 | 404
translate.googleapis.com | 403 | 404
cloud.google.com | 403 | 200
s2s.t13.io | 403 | 200
urs.techrepublic.com | 403 | 404
guc-dealer.spotify.com | 403 | 401
static.s2s.t13.io | 403 | 200
cdn.fuseplatform.net | 403 | 403
t.mookie1.com | 403 | 200
user-content.gitlab-static.net | 403 | 404
sp-bootstrap.spotifycdn.com | 403 | 403
apttherapy.amp.permutive.com | 403 | 200
p.aaxads.com | 403 | 204
publisher-config.unityads.unity3d.com | 403 | 502
tasks-pa.googleapis.com | 403 | 404
fresnel.vimeocdn.com | 403 | 405
ookla-d.openx.net | 403 | 200
collector-pxss13u803.px-cloud.net | 403 | 404
spoti.fi | 403 | 200
www.spotify.com | 403 | 200
iam.clients6.google.com | 403 | 404
ajax.googleapis.com | 403 | 200
log.olark.com | 403 | 200
api.veed.io | 403 | 200
api.spotify.com | 403 | 200
gew-spclient.spotify.com | 403 | 200
developers.google.com | 403 | 200
cdn.wootric.com | 403 | 200
firebasestorage.googleapis.com | 403 | 404
rtb.openx.net | 403 | 404
interaction.apester.com | 403 | 404
api.btloader.com | 403 | 404
dc.glbtls.t.co | 403 | 404
2e4b93d1-a8ae-4a89-8885-6109135ac0de.prmutv.co | 403 | 404
ad.mrtnsvr.com | 403 | 404
pixel-static.spotify.com | 403 | 403
firebaseperusertopics-pa.googleapis.com | 403 | 404
api.floors.dev | 403 | 404
tag.wknd.ai | 403 | 404
geomobileservices-pa.googleapis.com | 403 | 404
pay.google.com | 403 | 200
sdk.waze.com | 403 | 200
developerprofiles-pa.clients6.google.com | 403 | 404
pixel.myappfree.com | 403 | 200
ejp.rlcdn.com | 403 | 404
extensions-auth.uc.r.appspot.com | 403 | 200
cloudsearch.googleapis.com | 403 | 404
chromesyncpasswords-pa.googleapis.com | 403 | 404
u.openx.net | 403 | 200
dev.visualwebsiteoptimizer.com | 403 | 200
pippio.com | 403 | 200
bionic.fullstory.com | 403 | 200
us-central1-adaptive-growth.cloudfunctions.net | 403 | 200
clienttoken.spotify.com | 403 | 404
growth-pa.googleapis.com | 403 | 404
static-cdn-test.google-cdn.public.springernature.app | 403 | 200
rs.fullstory.com | 403 | 404
cdn.pdst.fm | 403 | 200
audio-akp-quic-control-spotify-com.akamaized.net | 403 | 403
img.apester.com | 403 | 200
pubcast-files.remixd.com | 403 | 403
notifications-pa.clients6.google.com | 403 | 404
query.petametrics.com | 403 | 404
sessions.bugsnag.com | 403 | 405
ipw.metadsp.co.uk | 403 | 404
codecov.io | 403 | 200
thind.unityads.unity3d.com | 403 | 200
signaler-pa.clients6.google.com | 403 | 404
csp.withgoogle.com | 403 | 200
contactsui-pa.googleapis.com | 403 | 404
footprints-pa.googleapis.com | 403 | 404
eu-u.openx.net | 403 | 200
jfapiprod.optimonk.com | 403 | 200
heads4-ak-spotify-com.akamaized.net | 403 | 403
journals.plos.org | 403 | 200
us-central1-amp-error-reporting.cloudfunctions.net | 403 | 200
johnwiley-d.openx.net | 403 | 200
edge.fullstory.com | 403 | 200
na.glbtls.t.co | 403 | 404
selfishsnake.com | 403 | 200
chat.google.com | 403 | 200
console.developers.google.com | 403 | 200
payments.google.com | 403 | 200
publift-d.openx.net | 403 | 200
wl.spotify.com | 403 | 404
serviceusage.clients6.google.com | 403 | 404
cdn.b0e8.com | 403 | 200
global.glbtls.t.co | 403 | 404
us-u.openx.net | 403 | 200
playatoms-pa.googleapis.com | 403 | 404
dealer.spotify.com | 403 | 401
d2fb08da-1c03-4c8a-978f-ad8a96b4c31f.prmutv.co | 403 | 404
events.apester.com | 403 | 404
hystericalcloth.com | 403 | 200
r.skimresources.com | 403 | 404
a.nel.cloudflare.com | 403 | 404
datamixer-pa.googleapis.com | 403 | 404
knrpc.olark.com | 403 | 502
gew-dealer.spotify.com | 403 | 401
t.skimresources.com | 403 | 404
dmp.brand-display.com | 403 | ?
audio-ak-spotify-com.akamaized.net | 403 | 403
live.chartboost.com | 403 | 200
login5.spotify.com | 403 | 404
api.rlcdn.com | 403 | 404
cdn.mxpnl.com | 403 | 404
d2fb08da-1c03-4c8a-978f-ad8a96b4c31f.partner.permutive.app | 403 | 200
i.clean.gg | 403 | 200
imp.control.kochava.com | 403 | 200
player-telemetry.vimeo.com | 403 | 405
idsync.rlcdn.com | 403 | 404
buysellads-d.openx.net | 403 | 200
id.rlcdn.com | 403 | 404
api.olark.com | 403 | 502
api-js.mixpanel.com | 403 | 200
cdn.sanity.io | 403 | 200
s.seedtag.com | 403 | 200
httpkafka.unityads.unity3d.com | 403 | 404
guc-spclient.spotify.com | 403 | 200
cm.ctnsnet.com | 403 | 404
notify.bugsnag.com | 403 | 405
accounts.spotify.com | 403 | 200
tr.snapchat.com | 403 | 200
appsitemsuggest-pa.clients6.google.com | 403 | 404
serve.onegraph.com | 403 | 200
spotify.com | 403 | 200
apikeys.clients6.google.com | 403 | 404
im.techrepublic.com | 403 | 403
cloudresourcemanager.clients6.google.com | 403 | 404
lens-pa.googleapis.com | 403 | 404
marvel-b2-cdn.bc0a.com | 403 | 200

</body>

</html>

**Comment by 0xRustlang** [comment]
اسپاتیفای خیلی ساله خودش مارو تحریم کرده و اکانت رو اگر با آی پی ایران استفاده میکردی میبست بعد چند هفته چون سودی براش نداریم و تبلیغی هم نمیتونه برامون پخش کنه که به دردمون بخوره

این قضیه البته مال چندین سال قبله
من بعدش صرفا با وی پی ان استفاده میکنم که البته الان به وی پی ان هم گیر میده به خاطر فشار طرف های قراردادش (مثل نتفلیکس که مدام وی پی ان هارو مینده) که البته فعلا اسپاتیفای از نتفلیکس کمتر حساسه که امیدوارم شدیدتر نشه و نشده باشه
