### ISSUE TITLE
ایمیل تغییر ریجن برای اکانت

### ISSUE THREAD

**Issue by 0xRustlang** [Hameds/GoogleBackup#60]
سلام
ایمیلی برای من اومده برای ایمیلم که چندماه پیش ساختم و تقریبا شاید به جز چندبار همون اوایل (زمانی که گوگل گیر نشده بود) فقط با آی پی ایران استفاده کردم

فکرکنم با وی پی ان یه کشور خاص اروپایی هم ساختمش و الان خیلی ماهه که صرفا با آی پی همون کشور اروپایی چکش میکنم و به جز زکان ساختنش که با موبایل ساختم و به جز شماره ایران که برای تایید دومرحله ای (نه تایید مالک بودن اکانت) بهش دادم و شلید یکی دوبار شش ماه پیش یا قبلش که شاید بدون وی پی ان چکش کرده باشم هیچ وقت دیگه بدون وی‌پی ان چکش نکردم و به طور کلی الان خیلی از اکانتام رو خیلی ماهه صرفا با آی پی همون کشور خاص چک میکنم

وی پی ان هام وی پی ان کرکی معتبر یا وی پی ان رایگان معتبر هستند و از تور، پراکسی های کثیف یا نرم افزارای عبور از تحریم قدیمی که برای ایران و چین ساخته شدن استفاده نکردم

ایمیلی برام اومده که گوگل ریجن اکانتم رو با وجود این همه مواظبت و با توجه به اینکه حتی گوگل پلی سرویس دستگاه من غیرفعاله و اکانت روش نیست، ریجن اکانتم رو از اون کشور اروپایی خاص به ایران تغییر داده که برام خیلی عجیب بود

این میتونه از شناسایی تایم زون یا این قضیه که ممکنه نرم افزار قبل فایروال کردنش بدون وی پی ان اتفاقی باز شده باشه دلیلش باشه

البته که ممکنه از شماره گیرنده کد ورود دومرحله ای که شماره ایران هست هم باشه

در ضمن به جز نرم افزار خود گوگل (سرچ) و کیبردش که صرفا برای تایپ صوتیش به هاطر مشکل چشمم استفاده میکنم و همیشه توی اسپلیت تونلینگ زدم که از وی پی ان رد نشن همه نرم افزارای گوگلم غیرفعالن از جمله پلی سرویس

البته که روت نیستم و رامم استوک هواوی هست

در کل این ایمیله

![Screenshot_20210517_024411](https://user-images.githubusercontent.com/49192003/118414450-d6918c80-b6b9-11eb-9eba-5c670df46fae.jpg)

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنونم که اطلاع دادید. به موضوع «ایمیل تغییر منطقه» که برای دوستان دیگر هم ارسال شده در متن اشاره خواهم کرد. گوگل روش‌های بسیاری برای پیدا کردن محل حساب کاربری دارد. 

</div>
