### ISSUE TITLE
gitlab access denied

### ISSUE THREAD

**Issue by behdad222** [Hameds/GoogleBackup#63]
تو fod همچنان باقی سرویس‌هایی که گوگل بهشون ۴۰۳ میداد در دسترس هستند
اما گیت‌لب اررور access denied میده

سرور خارج fod روی هتزنر هست که توسط گوگل بلاک شده و 403 میده
اما یک اینترفیس توسط wrap (1.1.1.1) بهش اضافه کردم
و ترافیک خروجی رو از اون رد میکنم و در نتیجه تونستم گوگل رو دور بزنم
این که چطور گیت‌لب متوجه شده و چطور بسته و چطور میشه دورش زد رو هنوز نمیدونم

**Comment by Hameds** [comment]
<div dir='rtl'>

@behdad222 خود گیت‌لب روی GCP نبود؟

</div>

**Comment by behdad222** [comment]
@Hameds 
فکر کنم پارسال مهاجرت کردند

در نهایت اون ارور google 403 رو نمیده

**Comment by Hameds** [comment]
@behdad222 

خود مهاجرت به GCP فکر می‌کنم قدیمی‌تر باشه. حتی قبل از مهاجرت هشدار داده بودند که برای دسترسی از ایران مشکل ایجاد می‌شه. البته این‌ها مربوط به قبل از بستن حساب‌هاست. https://about.gitlab.com/blog/2018/07/19/gcp-move-update/
