### ISSUE TITLE
گستردگی ماجرا در سرویس های همکار

### ISSUE THREAD

**Issue by mniik** [Hameds/GoogleBackup#7]
<div dir=rtl>به نظرم سرویس ها فقط مختص گوگل نیستند، الان حتی سایت tinypng.com هم ارور 403 میده.
<br><br>
اطلاعات مربوط به term of use سایت tinypng:
</div>
<br><br>
Google LLC, California, USA - Tinify uses Google Cloud Platform for website hosting, information technology and infrastructure services. Your personal data and purchase information is stored with Google. Tinify has a data processor contract with Google for processing of personal data and Google has certified to the EU-US Privacy Shield.

**Comment by Hameds** [comment]
<div dir='rtl'>

اگر سرویسی از زیرساخت ابری گوگل (GCP) استفاده کند ممکن است از این ماجرا تاثیر گرفته باشد. مثلاً اسپاتیفای که کاربران گزارش کرده‌اند در ورود حتی با VPN مشکل دارند. به لیست سرویس‌هایی که تاثیر گرفته‌اند اضافه شد

</div>

**Comment by Danial-Alh** [comment]
سایت [overleaf](https://www.overleaf.com/) هم فکر میکنم که خراب شده باشه.
