### ISSUE TITLE
نرم افزار Windscribe

### ISSUE THREAD

**Issue by BehdadEs** [Hameds/GoogleBackup#9]
<div dir='rtl'>
من و چند نفر دیگه برای دانلود بک آپ از سرویس Windscribe استفاده کردیم و بدون مشکل دانلود شد. <br>
سرویس تست شده ای هست و مشکلی نداشته <br>
تست های نشتی هم انجام شده و مشکلی نداشتن هیج کدوم
</div>

**Comment by Hameds** [comment]
سپاس از شما. به متن اضافه شد
